version: 2.1

workspace_root: &workspace_root ~/workspace
node_modules_dir: &node_modules_dir node_modules/
yarnpkg_cache_dir: &yarnpkg_cache_dir ./.cache/yarn
timezone: &timezone Asia/Tokyo

executors:
  node_lts:
    working_directory: *workspace_root
    environment:
      YARN_CACHE_FOLDER: *yarnpkg_cache_dir
      TZ: *timezone
    docker:
      - image: circleci/node:8.16.0

  node_latest:
    working_directory: *workspace_root
    environment:
      YARN_CACHE_FOLDER: *yarnpkg_cache_dir
      TZ: *timezone
    docker:
      - image: circleci/node:11.15.0

commands:
  cmd_restore_cache:
    steps:
      - restore_cache:
          keys:
            - v1-dep-{{ arch }}-{{ checksum "yarn.lock" }}

  cmd_save_cache:
    steps:
      - save_cache:
          key: v1-dep-{{ arch }}-{{ checksum "yarn.lock" }}-{{ epoch }}
          paths:
            - *yarnpkg_cache_dir

  cmd_show_env:
    steps:
      - run:
          command: |
            yarn --version
            yarn cache dir
            node -v

  cmd_install_dependencies:
    steps:
      - run: yarn

  cmd_build:
    steps:
      - run: yarn build

  cmd_lint:
    steps:
      - run: yarn lint

  cmd_check_fmt:
    steps:
      - run: yarn check_fmt

  cmd_test:
    steps:
      - run: yarn test

  cmd_release:
    steps:
      - run: npx semantic-release

  cmd_attach_workspace:
    steps:
      - attach_workspace:
          at: *workspace_root

  cmd_persist_dependencies_to_workspace:
    steps:
      - persist_to_workspace:
          root: *workspace_root
          paths:
            - *node_modules_dir
            - *yarnpkg_cache_dir

jobs:
  dependencies:
    executor: node_latest
    steps:
      - checkout
      - cmd_show_env
      - cmd_restore_cache
      - cmd_install_dependencies
      - cmd_save_cache
      - cmd_persist_dependencies_to_workspace

  lint:
    executor: node_latest
    steps:
      - checkout
      - cmd_attach_workspace
      - cmd_show_env
      - cmd_install_dependencies
      - cmd_lint

  check_fmt:
    executor: node_latest
    steps:
      - checkout
      - cmd_attach_workspace
      - cmd_show_env
      - cmd_install_dependencies
      - cmd_check_fmt

  test_in_node_lts:
    executor: node_lts
    steps:
      - checkout
      - cmd_attach_workspace
      - cmd_show_env
      - cmd_install_dependencies
      - cmd_build
      - cmd_test

  test_in_node_latest:
    executor: node_latest
    steps:
      - checkout
      - cmd_attach_workspace
      - cmd_show_env
      - cmd_install_dependencies
      - cmd_build
      - cmd_test

  release:
    executor: node_latest
    steps:
      - checkout
      - cmd_attach_workspace
      - cmd_show_env
      - cmd_install_dependencies
      - cmd_build
      - cmd_release

workflows:
  version: 2
  build_and_test:
    jobs:
      - dependencies
      - lint:
          requires:
            - dependencies
      - check_fmt:
          requires:
            - dependencies
      - test_in_node_lts:
          requires:
            - dependencies
      - test_in_node_latest:
          requires:
            - dependencies
  test_and_release:
    triggers:
      - schedule:
          cron: '0 0 * * 0'
          filters:
            branches:
              only:
                - master
    jobs:
      - dependencies
      - lint:
          requires:
            - dependencies
      - check_fmt:
          requires:
            - dependencies
      - test_in_node_lts:
          requires:
            - dependencies
      - test_in_node_latest:
          requires:
            - dependencies
      - release:
          requires:
            - lint
            - check_fmt
            - test_in_node_lts
            - test_in_node_latest
